package com.kynsoft.report.infrastructure.services;
import com.kynsoft.report.domain.dto.*;
import com.kynsoft.report.domain.services.ICajaOficialService;
import com.kynsoft.report.infrastructure.entity.*;
import com.kynsoft.report.infrastructure.repository.command.*;
import com.kynsoft.report.infrastructure.repository.query.*;
import com.kynsoft.report.infrastructure.security.*;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;
import java.time.*;
import java.util.*;

@Service @Transactional
public class CajaOficialServiceImpl implements ICajaOficialService {
 private final FondoCajaAutorizadoWriteDataJPARepository fondoWrite; private final FondoCajaAutorizadoReadDataJPARepository fondoRead; private final ActaResponsabilidadCajaWriteDataJPARepository actaWrite; private final ActaResponsabilidadCajaReadDataJPARepository actaRead; private final IncidenciaArqueoCajaWriteDataJPARepository incidenciaWrite; private final IncidenciaArqueoCajaReadDataJPARepository incidenciaRead; private final ArqueoCajaReadDataJPARepository arqueoRead; private final MovimientoCajaReadDataJPARepository movimientoRead;
 public CajaOficialServiceImpl(FondoCajaAutorizadoWriteDataJPARepository fondoWrite,FondoCajaAutorizadoReadDataJPARepository fondoRead,ActaResponsabilidadCajaWriteDataJPARepository actaWrite,ActaResponsabilidadCajaReadDataJPARepository actaRead,IncidenciaArqueoCajaWriteDataJPARepository incidenciaWrite,IncidenciaArqueoCajaReadDataJPARepository incidenciaRead,ArqueoCajaReadDataJPARepository arqueoRead,MovimientoCajaReadDataJPARepository movimientoRead){this.fondoWrite=fondoWrite;this.fondoRead=fondoRead;this.actaWrite=actaWrite;this.actaRead=actaRead;this.incidenciaWrite=incidenciaWrite;this.incidenciaRead=incidenciaRead;this.arqueoRead=arqueoRead;this.movimientoRead=movimientoRead;}
 public FondoCajaDto guardarFondo(FondoCajaRequest r){ if(r==null||r.getFincaId()==null||r.getTipo()==null||r.getImporteAutorizado()==null||r.getImporteAutorizado()<0) throw new IllegalArgumentException("Finca, tipo e importe autorizado válido son obligatorios."); TenantValidator.validateWriteAccess(r.getFincaId()); FondoCajaAutorizado f=fondoWrite.findForUpdate(r.getFincaId(),r.getTipo()).orElseGet(()->{FondoCajaAutorizado n=new FondoCajaAutorizado();n.setId(UUID.randomUUID());n.setFincaId(r.getFincaId());n.setTipo(r.getTipo());return n;}); f.setImporteAutorizado(r.getImporteAutorizado());f.setObservaciones(txt(r.getObservaciones()));f.setActivo(r.getActivo()==null||r.getActivo());fondoWrite.save(f);return fondo(f); }
 public List<FondoCajaDto> listarFondos(UUID fincaId){ lectura(fincaId);return fondoRead.findByFincaIdOrderByTipo(fincaId).stream().map(this::fondo).toList(); }
 public UUID crearActa(ActaResponsabilidadCajaRequest r){if(r==null||r.getFincaId()==null||txt(r.getCustodioNombre())==null)throw new IllegalArgumentException("Finca y custodio son obligatorios.");TenantValidator.validateWriteAccess(r.getFincaId());if(actaRead.existsByFincaIdAndEstado(r.getFincaId(),EstadoActaResponsabilidadCaja.ACTIVA))throw new IllegalArgumentException("Ya existe un acta de responsabilidad activa para la finca.");ActaResponsabilidadCaja a=new ActaResponsabilidadCaja();a.setId(UUID.randomUUID());a.setNumero(actaWrite.siguienteNumero());a.setFincaId(r.getFincaId());a.setCustodioId(r.getCustodioId());a.setCustodioNombre(txt(r.getCustodioNombre()));a.setUsuarioEmisorId(TenantContext.getUsuarioId());a.setFechaInicio(LocalDateTime.now());a.setEstado(EstadoActaResponsabilidadCaja.ACTIVA);a.setObservaciones(txt(r.getObservaciones()));actaWrite.save(a);return a.getId();}
 public void cerrarActa(UUID id,String observaciones){ActaResponsabilidadCaja a=actaWrite.findByIdForUpdate(id).orElseThrow(()->new IllegalArgumentException("Acta no encontrada."));TenantValidator.validateWriteAccess(a.getFincaId());if(a.getEstado()!=EstadoActaResponsabilidadCaja.ACTIVA)throw new IllegalArgumentException("El acta ya fue cerrada.");a.setEstado(EstadoActaResponsabilidadCaja.CERRADA);a.setFechaCierre(LocalDateTime.now());if(txt(observaciones)!=null)a.setObservaciones((a.getObservaciones()==null?"":a.getObservaciones()+"\n")+"Cierre: "+txt(observaciones));actaWrite.save(a);}
 public List<ActaResponsabilidadCajaDto> listarActas(UUID fincaId){lectura(fincaId);return actaRead.findByFincaIdOrderByFechaInicioDesc(fincaId).stream().map(this::acta).toList();}
 public UUID crearIncidencia(CrearIncidenciaArqueoCajaRequest r){if(r==null||r.getArqueoCajaId()==null||txt(r.getExpediente())==null||txt(r.getDescripcion())==null)throw new IllegalArgumentException("Arqueo, expediente y descripción son obligatorios.");if(incidenciaRead.existsByArqueoCajaId(r.getArqueoCajaId()))throw new IllegalArgumentException("El arqueo ya tiene una incidencia vinculada.");ArqueoCaja a=arqueoRead.findById(r.getArqueoCajaId()).orElseThrow(()->new IllegalArgumentException("Arqueo no encontrado."));TenantValidator.validateWriteAccess(a.getFincaId());if(a.getEstado()!=EstadoArqueoCaja.CERRADO||a.getDiferencia()==null||Math.abs(a.getDiferencia())<.000001)throw new IllegalArgumentException("Solo un arqueo cerrado con diferencia puede generar expediente.");IncidenciaArqueoCaja i=new IncidenciaArqueoCaja();i.setId(UUID.randomUUID());i.setArqueoCajaId(a.getId());i.setFincaId(a.getFincaId());i.setTipo(a.getDiferencia()<0?TipoIncidenciaArqueoCaja.FALTANTE:TipoIncidenciaArqueoCaja.SOBRANTE);i.setImporte(Math.abs(a.getDiferencia()));i.setExpediente(txt(r.getExpediente()));i.setDescripcion(txt(r.getDescripcion()));i.setEstado(EstadoIncidenciaArqueoCaja.PENDIENTE);i.setCreadoPorId(TenantContext.getUsuarioId());i.setFechaCreacion(LocalDateTime.now());incidenciaWrite.save(i);return i.getId();}
 public void actualizarIncidencia(UUID id,ActualizarIncidenciaArqueoCajaRequest r){if(r==null||r.getEstado()==null)throw new IllegalArgumentException("El estado es obligatorio.");IncidenciaArqueoCaja i=incidenciaWrite.findByIdForUpdate(id).orElseThrow(()->new IllegalArgumentException("Incidencia no encontrada."));TenantValidator.validateWriteAccess(i.getFincaId());if(i.getEstado()==EstadoIncidenciaArqueoCaja.RESUELTA||i.getEstado()==EstadoIncidenciaArqueoCaja.RECHAZADA)throw new IllegalArgumentException("La incidencia tiene estado terminal.");i.setEstado(r.getEstado());if(r.getEstado()==EstadoIncidenciaArqueoCaja.APROBADA||r.getEstado()==EstadoIncidenciaArqueoCaja.RESUELTA||r.getEstado()==EstadoIncidenciaArqueoCaja.RECHAZADA){i.setAprobadoPorId(TenantContext.getUsuarioId());i.setFechaResolucion(LocalDateTime.now());}if(txt(r.getObservaciones())!=null)i.setObservaciones(txt(r.getObservaciones()));incidenciaWrite.save(i);}
 public List<IncidenciaArqueoCajaDto> listarIncidencias(UUID fincaId){lectura(fincaId);return incidenciaRead.findByFincaIdOrderByFechaCreacionDesc(fincaId).stream().map(this::incidencia).toList();}
 public TableroControlCajaDto tablero(UUID fincaId,int anio,int mes){lectura(fincaId);if(mes<1||mes>12)throw new IllegalArgumentException("Mes inválido.");LocalDateTime ini=YearMonth.of(anio,mes).atDay(1).atStartOfDay(), fin=YearMonth.of(anio,mes).plusMonths(1).atDay(1).atStartOfDay();List<ArqueoCaja> as=arqueoRead.findByFincaIdOrderByFechaAperturaDesc(fincaId).stream().filter(a->!a.getFechaApertura().isBefore(ini)&&a.getFechaApertura().isBefore(fin)).toList();Map<TipoFondoCaja,Double> fondos=new HashMap<>();fondoRead.findByFincaIdOrderByTipo(fincaId).stream().filter(f->Boolean.TRUE.equals(f.getActivo())).forEach(f->fondos.put(f.getTipo(),f.getImporteAutorizado()));double saldo=Math.max(0d,val(movimientoRead.saldoByFincaId(fincaId)));return TableroControlCajaDto.builder().fincaId(fincaId).anio(anio).mes(mes).arqueosDelMes((long)as.size()).arqueosCerrados(as.stream().filter(a->a.getEstado()==EstadoArqueoCaja.CERRADO).count()).arqueosAbiertos(as.stream().filter(a->a.getEstado()==EstadoArqueoCaja.ABIERTO).count()).cumplimientoArqueoMensual(!as.isEmpty()).saldoPorDepositar(saldo).depositoPendiente(saldo>.000001).fondoCambioAutorizado(fondos.getOrDefault(TipoFondoCaja.CAMBIO,0d)).fondoPagosMenoresAutorizado(fondos.getOrDefault(TipoFondoCaja.PAGOS_MENORES,0d)).fondoNominaAutorizado(fondos.getOrDefault(TipoFondoCaja.NOMINA,0d)).incidenciasPendientes(incidenciaRead.countByFincaIdAndEstadoIn(fincaId,List.of(EstadoIncidenciaArqueoCaja.PENDIENTE,EstadoIncidenciaArqueoCaja.EN_REVISION,EstadoIncidenciaArqueoCaja.APROBADA))).build();}
 private void lectura(UUID finca){if(finca==null)throw new IllegalArgumentException("La finca es obligatoria.");TenantValidator.validateReadAccess(finca);} private String txt(String s){return s==null||s.isBlank()?null:s.trim();}private double val(Double d){return d==null?0:d;}private FondoCajaDto fondo(FondoCajaAutorizado f){return FondoCajaDto.builder().id(f.getId()).fincaId(f.getFincaId()).tipo(f.getTipo()).importeAutorizado(f.getImporteAutorizado()).observaciones(f.getObservaciones()).activo(f.getActivo()).build();} private ActaResponsabilidadCajaDto acta(ActaResponsabilidadCaja a){return ActaResponsabilidadCajaDto.builder().id(a.getId()).numero(a.getNumero()).fincaId(a.getFincaId()).custodioId(a.getCustodioId()).custodioNombre(a.getCustodioNombre()).usuarioEmisorId(a.getUsuarioEmisorId()).fechaInicio(a.getFechaInicio()).fechaCierre(a.getFechaCierre()).estado(a.getEstado()).observaciones(a.getObservaciones()).build();}private IncidenciaArqueoCajaDto incidencia(IncidenciaArqueoCaja i){return IncidenciaArqueoCajaDto.builder().id(i.getId()).arqueoCajaId(i.getArqueoCajaId()).fincaId(i.getFincaId()).tipo(i.getTipo()).importe(i.getImporte()).expediente(i.getExpediente()).descripcion(i.getDescripcion()).estado(i.getEstado()).creadoPorId(i.getCreadoPorId()).aprobadoPorId(i.getAprobadoPorId()).fechaCreacion(i.getFechaCreacion()).fechaResolucion(i.getFechaResolucion()).observaciones(i.getObservaciones()).build();}}
