package com.kynsoft.report.infrastructure.services;
import com.itextpdf.kernel.font.PdfFont; import com.itextpdf.kernel.font.PdfFontFactory; import com.itextpdf.kernel.geom.PageSize; import com.itextpdf.kernel.pdf.*; import com.itextpdf.layout.Document; import com.itextpdf.layout.element.*; import com.itextpdf.layout.properties.TextAlignment;
import com.kynsoft.report.domain.dto.*; import com.kynsoft.report.domain.services.IConteoFisicoAlmacenService; import org.springframework.stereotype.Service; import java.io.ByteArrayOutputStream;
/** PDF imprimible del expediente SC-2-15 y, cuando existe, su ajuste SC-2-16. */
@Service public class ConteoFisicoAlmacenPdfService {
 private final IConteoFisicoAlmacenService service; public ConteoFisicoAlmacenPdfService(IConteoFisicoAlmacenService service){this.service=service;}
 public byte[] generar(java.util.UUID id){ ConteoFisicoDetalleDto c=service.detalle(id); try(ByteArrayOutputStream out=new ByteArrayOutputStream()){Document d=new Document(new PdfDocument(new PdfWriter(out)),PageSize.A4); PdfFont n=PdfFontFactory.createFont("Helvetica"),b=PdfFontFactory.createFont("Helvetica-Bold"); d.setMargins(30,30,30,30);d.add(new Paragraph("INVENTARIO FÍSICO DE ALMACÉN — SC-2-15").setFont(b).setFontSize(14).setTextAlignment(TextAlignment.CENTER));d.add(new Paragraph("No. "+c.getNumero()+" | Estado: "+c.getEstado()+(c.getNumeroAjuste()==null?"":" | Ajuste SC-2-16: "+c.getNumeroAjuste())).setFont(n).setFontSize(9).setTextAlignment(TextAlignment.CENTER));Table info=new Table(new float[]{1,2}).useAllAvailableWidth().setMarginTop(10);fila(info,"Almacén",c.getAlmacenNombre(),b,n);fila(info,"Responsable",c.getResponsableConteo(),b,n);fila(info,"Verificado por",c.getVerificadoPor(),b,n);fila(info,"Autorizado por",c.getAutorizadoPor(),b,n);fila(info,"Observaciones",c.getObservacionesCierre()==null?c.getObservacionesApertura():c.getObservacionesCierre(),b,n);d.add(info);Table t=new Table(new float[]{2,1,1,1,1.4f}).useAllAvailableWidth().setMarginTop(12);for(String h:new String[]{"Producto","Unidad","Teórico","Físico","Diferencia"})t.addHeaderCell(cell(h,b));for(ConteoFisicoLineaDto l:c.getLineas()){t.addCell(cell(l.getProductoNombre(),n));t.addCell(cell(text(l.getUnidadMedida()),n));t.addCell(cell(num(l.getExistenciaTeorica()),n));t.addCell(cell(l.getExistenciaFisica()==null?"Pendiente":num(l.getExistenciaFisica()),n));t.addCell(cell(l.getDiferencia()==null?"Pendiente":num(l.getDiferencia()),n));}d.add(t);d.add(new Paragraph("El documento conserva la existencia teórica al momento de apertura. Toda diferencia se registra exclusivamente al cierre como ajuste SC-2-16 y queda enlazada a este expediente.").setFont(n).setFontSize(8).setMarginTop(12));d.close();return out.toByteArray();}catch(Exception e){throw new IllegalStateException("No se pudo generar el PDF del inventario físico.",e);}}
 private void fila(Table t,String a,String z,PdfFont b,PdfFont n){t.addCell(cell(a,b));t.addCell(cell(text(z),n));} private Cell cell(String x,PdfFont f){return new Cell().add(new Paragraph(x).setFont(f).setFontSize(8));}private String text(String x){return x==null||x.isBlank()?"-":x;}private String num(Double x){return String.format("%,.4f",x);}
}
