spring.application.name= report
spring.profiles.active=${RC_ACTIVE_PROFILE:dev}
#spring.config.import=configserver:http://${RC_SERVER_CONFIG:localhost}:8081
#spring.cloud.config.username=root
#spring.cloud.config.password=S3cr3tp4swordConf1G

# Configuraci\u00c3\u00b3n para el directorio de archivos Jasper
jasper.reports.output.path=${JASPER_OUTPUT_PATH:/app/jasper-output}
# Prometheus Metrics Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

